export const assetTypes = [
  "STIG Bond",
  "IG Bond",
  "Indiv. Bonds",
  "Bank Loan",
  "Mixed Credit",
  "High Yield",
  "Preferred - Fixed Maturity",
  "Preferred - Fixed Floating",
  "Preferred Fund",
  "Preferred - Perpetual Floating",
  "Preferred - Perpetual Fixed",
  "Hedge",
  "Crypto",
  "Common",
  "BDC Equity",
  "Equity / Options",
  "Common Int'l",
];
