export const REVALIDATE_TIME = 1000 * 60 * 15; // 15 minutes
export const STALE_TIME = 1000 * 60 * 60 * 24; // 24 hours

export const tickerTypeKeys = [
  "CS",
  "PFD",
  "WARRANT",
  "RIGHT",
  "UNIT",
  "BASKET",
  "ETF",
  "ETN",
  "ETV",
  "ETS",
  "SP",
  "ADRC",
  "ADRP",
  "ADRW",
  "ADRR",
  "CEF",
  "OEF",
  "LT",
  "OS",
  "GDR",
  "NYRS",
  "BOND",
  "AGEN",
  "EQLK",
  "OTHER",
] as const;
export type TickerType = (typeof tickerTypeKeys)[number];
export const tickerTypes = {
  CS: "Common Stock",
  PFD: "Preferred Stock",
  WARRANT: "Warrant",
  RIGHT: "Rights",
  UNIT: "Unit",
  BASKET: "Basket",
  ETF: "Exchange Traded Fund",
  ETN: "Exchange Traded Note",
  ETV: "Exchange Traded Vehicle",
  ETS: "Single-security ETF",
  SP: "Structured Product",
  ADRC: "American Depository Receipt Common",
  ADRP: "American Depository Receipt Preferred",
  ADRW: "American Depository Receipt Warrants",
  ADRR: "American Depository Receipt Rights",
  CEF: "Closed-End Mutual Fund",
  OEF: "Open-End Mutual Fund",
  LT: "Liquidating Trust",
  OS: "Ordinary Shares",
  GDR: "Global Depository Receipts",
  NYRS: "New York Registry Shares",
  BOND: "Corporate Bond",
  AGEN: "Agency Bond",
  EQLK: "Equity Linked Bond",
  OTHER: "Other Security Type",
} satisfies Record<TickerType, string>;
